title: [Architects.guru]
description: [Buduj wysokiej jako≈õci oprogramowanie]
show_downloads: false
google_analytics: G-F5QKELK8MV
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
